---
- name: Disable UFW
  hosts: all
  become: yes

  vars_files:
    - vars/secrets.yml  # Ensure the correct relative path
  


  tasks:
    - name: Disable UFW
      community.general.ufw:
        state: disabled

