---
- name: Basic Update software
  hosts: all
  gather_facts: yes
  become: yes

  vars_files:
    - vars/secrets.yml  # Ensure the correct relative path

  tasks:
    - name: Disable UFW
      community.general.ufw:
        state: disabled

    - name: Remove Google Chrome APT source list
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/google-chrome.list
        state: absent

    - name: Remove APT lock files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/dpkg/lock
        - /var/lib/dpkg/lock-frontend
        - /var/lib/apt/lists/lock
        - /var/cache/apt/archives/lock
     
    - name: Run dpkg configure to fix broken packages
      ansible.builtin.command: dpkg --configure -a
      become: yes
      register: dpkg_configure_result
      changed_when: dpkg_configure_result.rc != 0
      ignore_errors: yes
      

    - name: Update using apt
      ansible.builtin.apt:
        name: "*"
        state: latest 



    - name: Allow SSH (port 22) from any source
      community.general.ufw:
        rule: allow
        port: "22"
        proto: tcp
        from_ip: any


    - name: Enable UFW
      community.general.ufw:
        state: enabled

